"""initial migration

Revision ID: 4df1860d63b8
Revises: 
Create Date: 2024-01-11 18:18:46.343258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4df1860d63b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency_data', schema=None) as batch_op:
        batch_op.drop_column('average_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_price', sa.FLOAT(precision=53), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
