"""Make source_id nullable

Revision ID: 4e2882c6f5e3
Revises: 
Create Date: 2023-11-16 19:20:42.315814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e2882c6f5e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.alter_column('source_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.alter_column('source_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
