"""Migracja3

Revision ID: 7976b4978399
Revises: 8e869f815dba
Create Date: 2023-11-18 18:01:45.791937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7976b4978399'
down_revision = '8e869f815dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255, collation='Polish_CI_AS'),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255, collation='Polish_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
