"""Migr

Revision ID: 8e869f815dba
Revises: 4e2882c6f5e3
Create Date: 2023-11-18 17:59:12.209387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e869f815dba'
down_revision = '4e2882c6f5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticker_sentiment', schema=None) as batch_op:
        batch_op.alter_column('ticker',
               existing_type=sa.VARCHAR(length=10, collation='Polish_CI_AS'),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticker_sentiment', schema=None) as batch_op:
        batch_op.alter_column('ticker',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10, collation='Polish_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
