"""Migracja4

Revision ID: 99b6942a4ef3
Revises: 7976b4978399
Create Date: 2023-11-18 19:52:07.932722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b6942a4ef3'
down_revision = '7976b4978399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=500, collation='Polish_CI_AS'),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500, collation='Polish_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
